#!/usr/bin/env bash

set -x

export CMD_PATH=$PWD
export PROJECT_NAME="${CMD_PATH##*/}"
echo $PROJECT_NAME
cd $CMD_PATH

git config --global user.email  "gnuhub@qq.com"
git config --global user.name   "gnuhub"
git config --global core.editor "vim"
git config --global pull.rebase false

git status
git add .
export message="$1"
if [ -z "$message" ];then
    export message="[just fix it]"
fi
git commit -a -m "$message"
git push origin HEAD

